<?php
const UTP_PLUGIN = 'unraid.theme.park';

function utp_plugin_dir() {
    return '/usr/local/emhttp/plugins/' . UTP_PLUGIN;
}

function utp_config_dir() {
    return '/boot/config/plugins/' . UTP_PLUGIN;
}

function utp_config_file() {
    return utp_config_dir() . '/' . UTP_PLUGIN . '.cfg';
}

function utp_default_config() {
    return [
        'enabled' => 'no',
        'theme' => 'dark',
        'upstream_ref' => 'themepark-dev/theme.park@1.22.0',
    ];
}

function utp_config() {
    if (function_exists('parse_plugin_cfg')) {
        $cfg = parse_plugin_cfg(UTP_PLUGIN);
        if (is_array($cfg) && count($cfg)) {
            return array_replace(utp_default_config(), $cfg);
        }
    }

    $file = utp_config_file();
    $cfg = is_file($file) ? parse_ini_file($file) : [];
    return array_replace(utp_default_config(), is_array($cfg) ? $cfg : []);
}

function utp_write_config($cfg) {
    if (!is_dir(utp_config_dir())) {
        mkdir(utp_config_dir(), 0755, true);
    }

    $safe = array_replace(utp_default_config(), $cfg);
    $lines = [];
    foreach ($safe as $key => $value) {
        $lines[] = $key . '="' . addcslashes((string)$value, "\\\"") . '"';
    }
    return file_put_contents(utp_config_file(), implode("\n", $lines) . "\n") !== false;
}

function utp_manifest_file() {
    return utp_plugin_dir() . '/themes/manifest.json';
}

function utp_themes() {
    $manifest = utp_manifest_file();
    $themes = is_file($manifest) ? json_decode(file_get_contents($manifest), true) : null;
    if (!is_array($themes)) {
        return [];
    }
    return $themes;
}

function utp_theme($theme_id) {
    $themes = utp_themes();
    return $themes[$theme_id] ?? null;
}

function utp_valid_theme_file($file) {
    return is_string($file) && preg_match('/\A[a-z0-9._-]+\.css\z/', $file);
}

function utp_generate_css($cfg = null) {
    $cfg = $cfg ?: utp_config();
    $enabled = ($cfg['enabled'] ?? 'no') === 'yes';
    $theme_id = $cfg['theme'] ?? 'dark';
    $theme = utp_theme($theme_id);

    $generated_dir = utp_plugin_dir() . '/generated';
    $sheets_dir = utp_plugin_dir() . '/sheets';
    if (!is_dir($generated_dir)) {
        mkdir($generated_dir, 0755, true);
    }
    if (!is_dir($sheets_dir)) {
        mkdir($sheets_dir, 0755, true);
    }

    $current_css = "/* Generated by Unraid Theme Park. */\n";
    if ($enabled && $theme && utp_valid_theme_file($theme['file'] ?? null)) {
        $current_css .= '@import url("/plugins/' . UTP_PLUGIN . '/themes/' . $theme['file'] . '");' . "\n";
    } else {
        $current_css .= "/* Theme disabled or unavailable. */\n";
    }

    $stamp = time();
    $global_css = "/* Generated by Unraid Theme Park. */\n";
    $global_css .= '@import url("/plugins/' . UTP_PLUGIN . '/generated/current.css?v=' . $stamp . '");' . "\n";

    $current_ok = file_put_contents($generated_dir . '/current.css', $current_css) !== false;
    $global_ok = file_put_contents($sheets_dir . '/ThemeParkGlobal.css', $global_css) !== false;

    return $current_ok && $global_ok;
}

function utp_current_status() {
    $cfg = utp_config();
    $theme = utp_theme($cfg['theme'] ?? 'dark');
    $enabled = ($cfg['enabled'] ?? 'no') === 'yes';
    $theme_name = $theme['name'] ?? 'Unknown';
    return [
        'enabled' => $enabled,
        'theme' => $cfg['theme'] ?? 'dark',
        'message' => $enabled ? "Enabled: $theme_name" : 'Disabled; stock styling is active.',
        'current_css' => utp_plugin_dir() . '/generated/current.css',
    ];
}
?>
